# Generated by Django 5.1.4 on 2025-01-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name_plural': 'Payment Status'},
        ),
        migrations.AlterModelOptions(
            name='usettings',
            options={'verbose_name_plural': 'USettings'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(),
        ),
    ]
