# Generated by Django 5.1.4 on 2025-01-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0004_alter_bill_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['payment_status', 'due_date']},
        ),
    ]
