# Generated by Django 5.1.4 on 2025-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0005_alter_bill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='recurring_count',
            field=models.IntegerField(default=0),
        ),
    ]
