# Generated by Django 5.1.4 on 2025-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0007_bill_created_at_bill_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='recurring_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
