# Generated by Django 5.1.5 on 2025-01-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0008_alter_bill_bill_month_alter_bill_recurring_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_month',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='recurring',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='recurring_count',
        ),
    ]
