# Generated by Django 5.1.5 on 2025-01-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0009_remove_bill_bill_month_remove_bill_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(),
        ),
    ]
