# Generated by Django 5.1.5 on 2025-01-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0010_alter_bill_amount_alter_bill_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='bill_id',
            new_name='bill',
        ),
        migrations.RenameField(
            model_name='usettings',
            old_name='user_id',
            new_name='user',
        ),
    ]
