# Generated by Django 5.1.5 on 2025-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0013_remove_paymentmethod_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='amount_payable',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
