# Generated by Django 5.1.5 on 2025-01-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billstracker', '0014_bill_amount_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='billstracker.bill'),
        ),
    ]
